$(document).ready(function(){
    $(".chapitre-1").click(function(){
    	$(".modal").removeClass("is-active");
    });
    $(".chapitre-2").click(function(){
    	$(".modal").addClass("is-active");
    });
    $(".chapitre-3").click(function(){
    	$(".modal").addClass("is-active");
    });
    $(".modal-close").click(function(){
    	$(".modal").removeClass("is-active");
    });
    $(".modal-background").click(function(){
    	$(".modal").removeClass("is-active");
    });
});
